version: "3"
services:
  mariadb:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=jefao123
      - MYSQL_DATABASE=vip-asterisk
      - MYSQL_USER=vip
      - MYSQL_PASSWORD=vip09092020
    ports:
      - 3306:3306
    volumes:
      - ./dbdata:/var/lib/mysql